services:
  tor:
    build: .
    container_name: tor-relay
    user: tor
    environment:
      - PASSWORD=${PASSWORD}
      - EXIT_NODES=
    ports:
      - "9050:9050"
      - "9051:9051"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "supervisorctl", "status", "tor"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  tor_data:
    driver: local
